version: '3.8'

services:
  backend:
    image: node:16
    container_name: message-backend
    command: 'bash -c "npm install && npm run dev"'
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    networks:
      - private

networks:
  private: