version: '3.8'

services:
  backend:
    image: node:16
    container_name: message-backend
    command: 'bash -c "npm install && npm run dev"'
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    networks:
      - private

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_ERLANG_COOKIE="eN0qba6e9EBijBErFB09N9C6GuIlk6WhxixeUqmY"
      # - RABBITMQ_DEFAULT_USER=admin
      # - RABBITMQ_DEFAULT_PASS=admin
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        # - ./build/rabbitmq/:/etc/rabbitmq
        - ./build/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
        - ./build/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
        - private

networks:
  private: